- name: Get instance facts
  ec2_instance_facts:
    region: "{{ region }}"
    filters:
      "tag:namespace": "{{namespace}}"
  register: ec2_facts

- name: Terminate instance
  ec2:
    state: absent
    region: "{{ region }}"
    instance_ids: "{{ item.instance_id }}"
    wait: yes
  with_items: "{{ ec2_facts.instances }}"
  when: item.state != 'terminated'